// Export formatters — plain text, SimplePractice, TherapyNotes, clipboard.

import { tauriInvoke } from '../core/storageBackend.js';
import { appendAudit } from '../core/auditLog.js';
import { emit } from '../core/eventBus.js';
import { displayDateShort } from '../utils/format.js';

// Plain text — safe paste into any EHR.
export function toPlainText(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const alias = encounter.patient_alias ? `Patient: ${encounter.patient_alias}\n` : '';
  return `Date: ${date}\n${alias}\n${note}\n`;
}

// SimplePractice — matches their progress note paste structure.
export function toSimplePractice(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Session Date: ${date}`,
    encounter.patient_alias ? `Client: ${encounter.patient_alias}` : '',
    '',
    note,
    '',
    '--- Generated by Tahlk | Provider review and sign-off completed ---',
  ].filter(l => l !== null).join('\n');
}

// TherapyNotes — matches their note import format.
export function toTherapyNotes(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Note Date: ${date}`,
    '',
    note,
    '',
    '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---',
  ].join('\n');
}

// Copy formatted text to system clipboard via Tauri.
export async function copyToClipboard(text, encounterId, format) {
  const { writeText } = window.__TAURI__?.['clipboard-manager'] ||
    window.__TAURI__?.clipboardManager || {};

  if (writeText) {
    await writeText(text);
  } else {
    await navigator.clipboard.writeText(text);
  }

  appendAudit(`note_audit_v1::${encounterId}`, 'note_exported', { format, method: 'clipboard' });
  emit('scribe:note_exported', { encounterId, format });
}

// Save to a .txt file via Tauri file dialog.
export async function saveToFile(text, encounter, format) {
  const date = (encounter.encounter_date || '').slice(0, 10).replace(/-/g, '');
  const alias = encounter.patient_alias ? `_${encounter.patient_alias.replace(/\s+/g, '-')}` : '';
  const suggestedName = `note_${date}${alias}.txt`;

  await tauriInvoke('export_note_to_file', { content: text, suggestedName });

  appendAudit(`note_audit_v1::${encounter.id}`, 'note_exported', { format, method: 'file' });
  emit('scribe:note_exported', { encounterId: encounter.id, format });
}
