// Export formatters — plain text, behavioral-health EHRs (SimplePractice,
// TherapyNotes), podiatry EHRs (ModMed, eClinicalWorks), clipboard, file.

import { tauriInvoke } from '../core/storageBackend.js';
import { appendAudit } from '../core/auditLog.js';
import { emit } from '../core/eventBus.js';
import { displayDateShort } from '../utils/format.js';
import { familyOf } from '../core/specialties.js';

// Plain text — safe paste into any EHR.
export function toPlainText(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const alias = encounter.patient_alias ? `Patient: ${encounter.patient_alias}\n` : '';
  return `Date: ${date}\n${alias}\n${note}\n`;
}

// SimplePractice — matches their progress note paste structure.
export function toSimplePractice(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Session Date: ${date}`,
    encounter.patient_alias ? `Client: ${encounter.patient_alias}` : '',
    '',
    note,
    '',
    '--- Generated by Tahlk | Provider review and sign-off completed ---',
  ].filter(l => l !== null).join('\n');
}

// TherapyNotes — matches their note import format.
export function toTherapyNotes(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Note Date: ${date}`,
    '',
    note,
    '',
    '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---',
  ].join('\n');
}

// Kareo / Tebra — SMB practice-management EHR; encounter-note paste structure.
export function toKareo(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const lines = [`Date of Service: ${date}`];
  if (encounter.patient_alias) lines.push(`Patient: ${encounter.patient_alias}`);
  lines.push('', note, '', '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---');
  return lines.join('\n');
}

// ModMed (EMA) — leading podiatry/derm EHR; encounter-note paste structure.
export function toModMed(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const lines = [`Date of Service: ${date}`];
  if (encounter.patient_alias) lines.push(`Patient: ${encounter.patient_alias}`);
  lines.push('', note, '', '--- Tahlk (AI-assisted) | Reviewed and signed by provider ---');
  return lines.join('\n');
}

// eClinicalWorks — multi-specialty EHR common in podiatry; progress-note paste.
export function toEclinicalWorks(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const lines = [`Encounter Date: ${date}`];
  if (encounter.patient_alias) lines.push(`Patient: ${encounter.patient_alias}`);
  lines.push('', note, '', '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---');
  return lines.join('\n');
}

// Export-target registry. `family: null` = universal; otherwise scoped to a
// specialty family (see core/specialties.js).
export const EXPORT_FORMATS = [
  { id: 'plain',          label: 'Plain text',     family: null,                fn: toPlainText },
  { id: 'simplepractice', label: 'SimplePractice', family: 'behavioral-health', fn: toSimplePractice },
  { id: 'therapynotes',   label: 'TherapyNotes',   family: 'behavioral-health', fn: toTherapyNotes },
  { id: 'kareo',          label: 'Kareo / Tebra',  family: 'behavioral-health', fn: toKareo },
  { id: 'modmed',         label: 'ModMed (EMA)',   family: 'podiatry',          fn: toModMed },
  { id: 'ecw',            label: 'eClinicalWorks', family: 'podiatry',          fn: toEclinicalWorks },
];

// Export targets for a provider: universal formats plus their specialty family.
// Unmapped/absent specialty → all formats (backward compatible).
export function exportFormatsFor(specialty) {
  const fam = familyOf(specialty);
  return EXPORT_FORMATS.filter(f => f.family === null || fam === null || f.family === fam);
}

// Dispatch by format id; unknown id falls back to plain text.
export function formatNote(id, note, encounter) {
  const fmt = EXPORT_FORMATS.find(f => f.id === id) || EXPORT_FORMATS[0];
  return fmt.fn(note, encounter);
}

// Copy formatted text to system clipboard via Tauri.
export async function copyToClipboard(text, encounterId, format) {
  const { writeText } = window.__TAURI__?.['clipboard-manager'] ||
    window.__TAURI__?.clipboardManager || {};

  if (writeText) {
    await writeText(text);
  } else {
    await navigator.clipboard.writeText(text);
  }

  appendAudit(`note_audit_v1::${encounterId}`, 'note_exported', { format, method: 'clipboard' });
  emit('scribe:note_exported', { encounterId, format });
}

// Save to a .txt file via Tauri file dialog.
export async function saveToFile(text, encounter, format) {
  const date = (encounter.encounter_date || '').slice(0, 10).replace(/-/g, '');
  const alias = encounter.patient_alias ? `_${encounter.patient_alias.replace(/\s+/g, '-')}` : '';
  const suggestedName = `note_${date}${alias}.txt`;

  await tauriInvoke('export_note_to_file', { content: text, suggestedName });

  appendAudit(`note_audit_v1::${encounter.id}`, 'note_exported', { format, method: 'file' });
  emit('scribe:note_exported', { encounterId: encounter.id, format });
}
